id: PB8CDABD4
initial_creation_type: ocr
source_metadata:
  volumes:
    2c8485f1d778435596b7d6f532a2afc6:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: འཕགས་པ་ཀུན་ནས་སྒོར་འཇུག་པའི་འོད་ཟེར་གཙུག་ཏོར་དྲི་མ་མེད་པར་སྣང་བའི་གཟུངས་བཀླག་ཅིང་མཆོད་རྟེན་བརྒྱ་རྩ་བརྒྱད་དམ།
        མཆོད་རྟེན་ལྔ་གདབ་པའི་ཆོ་ག་མདོ་སྡེ་ལས་བསྡུས་པ།
      total_pages: 1044
      volume_number: 38
